
pipeline {
  
  agent  any
  tools
  {
    maven 'Maven'
  }
     stages('First Stage')
  {
        stage('Build')
    {
     steps 
     {
      echo 'Building app'
       sh "mvn clean"
      }
      }
     
     stage('Deploy')
     {
     steps 
     {
      echo 'Deploying app'
      }
      }

}
}
