
pipeline {
  
  agent  any
  tools
  {
    maven 'Maven'
  }
     stages('First Stage')
  {
        stage('Checkout') {
            git url: 'https://github.com/piomin/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

}
}
